// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

// Generated by the catalogue sync — every address a product used to have, pointing at the one
// it has now. The sheet decides a product's address, so renaming one in the sheet moves its
// page; this is what stops a link already shared on WhatsApp or Instagram from going dead.
// Astro emits a small redirecting page per entry under `output: 'static'`, which is all a
// static host can do and is enough for a browser following a link.
import redirects from './src/redirects.json' with { type: 'json' };

// PLAN.md §10.1 — an absolute `site` is what makes every generated URL canonical.
export default defineConfig({
  site: 'https://jadauco.com',
  output: 'static',
  trailingSlash: 'always',
  redirects,
  integrations: [sitemap()],
});
